/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/nav/AboutView': RouteRecordInfo<'/nav/AboutView', '/nav/AboutView', Record<never, never>, Record<never, never>>,
    '/nav/HelloWorld': RouteRecordInfo<'/nav/HelloWorld', '/nav/HelloWorld', Record<never, never>, Record<never, never>>,
    '/nav/HomeView': RouteRecordInfo<'/nav/HomeView', '/nav/HomeView', Record<never, never>, Record<never, never>>,
    '/nav/LoginView': RouteRecordInfo<'/nav/LoginView', '/nav/LoginView', Record<never, never>, Record<never, never>>,
    '/nav/ProcessAdjustView': RouteRecordInfo<'/nav/ProcessAdjustView', '/nav/ProcessAdjustView', Record<never, never>, Record<never, never>>,
    '/nav/ProcessManageView': RouteRecordInfo<'/nav/ProcessManageView', '/nav/ProcessManageView', Record<never, never>, Record<never, never>>,
    '/nav/ProcessStatusView': RouteRecordInfo<'/nav/ProcessStatusView', '/nav/ProcessStatusView', Record<never, never>, Record<never, never>>,
    '/nav/TaskView': RouteRecordInfo<'/nav/TaskView', '/nav/TaskView', Record<never, never>, Record<never, never>>,
    '/nav/TodoView': RouteRecordInfo<'/nav/TodoView', '/nav/TodoView', Record<never, never>, Record<never, never>>,
    '/nav/UserView': RouteRecordInfo<'/nav/UserView', '/nav/UserView', Record<never, never>, Record<never, never>>,
  }
}
