/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
import { DUMMY_BASE_URL, assertParamExists, setSearchParams, toPathString, createRequestFunction } from '../common';
import { BASE_PATH, type RequestArgs, BaseAPI, operationServerMap } from '../base';
import type { Process, ProcessRequest, FormField, FlowNode, User, HistoryLog, ProcessInstance } from '../models';

/**
 * ProcessAPIAxiosParamCreator - 参数创建器
 */
export const ProcessAPIAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Deploy a new process with BPMN file
         * @param {ProcessRequest} request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployProcess: async (request: ProcessRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('deployProcess', 'request', request);
            const localVarPath = `/api/process/deploy`;
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new FormData();

            if (request.name) {
                localVarFormParams.append('name', request.name);
            }
            if (request.file) {
                localVarFormParams.append('file', request.file);
            }

            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves all process definitions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllDefinitions: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/process/definitions`;
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves all running process instances
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllInstances: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/process/instances`;
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ★★★ 新增：獲取我的申請紀錄 ★★★
         * Retrieves process instances started by current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyProcessInstances: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/process/my-instances`;
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves process instance diagram and current task
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProcessInstanceDiagram: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('getProcessInstanceDiagram', 'id', id);
            const localVarPath = `/api/process/instances/{id}/diagram`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves process definition diagram
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProcessDefinitionDiagram: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('getProcessDefinitionDiagram', 'id', id);
            const localVarPath = `/api/process/definitions/{id}/diagram`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves form fields for a process definition
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProcessFormFields: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('getProcessFormFields', 'id', id);
            const localVarPath = `/api/process/definitions/{id}/form`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ★★★ 新增：獲取特定節點的表單 (用於跳關) ★★★
         * @param {string} processInstanceId
         * @param {string} nodeId
         * @param {*} [options]
         */
        getNodeFormFields: async (processInstanceId: string, nodeId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('getNodeFormFields', 'processInstanceId', processInstanceId);
            assertParamExists('getNodeFormFields', 'nodeId', nodeId);
            const localVarPath = `/api/process/instances/{processInstanceId}/nodes/{nodeId}/form`
                .replace(`{${"processInstanceId"}}`, encodeURIComponent(String(processInstanceId)))
                .replace(`{${"nodeId"}}`, encodeURIComponent(String(nodeId)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves form fields for a user task
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTaskFormFields: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('getTaskFormFields', 'id', id);
            const localVarPath = `/api/process/tasks/{id}/form`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Starts a process instance
         * @param {ProcessRequest} processRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        startProcess: async (processRequest: ProcessRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('startProcess', 'processRequest', processRequest);
            const localVarPath = `/api/process/start`;
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const serializedRequest = {
                processDefinitionId: processRequest.processDefinitionId,
                variables: processRequest.variables || {}
            };

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            localVarRequestOptions.data = JSON.stringify(serializedRequest);

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Enables or disables a process definition
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        toggleProcessStatus: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('toggleProcessStatus', 'id', id);
            const localVarPath = `/api/process/definitions/{id}/toggle`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves all available users for task assignment
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUsers: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/process/users`;
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves all flow nodes for a process instance
         * @param {string} processInstanceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFlowNodes: async (processInstanceId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('getFlowNodes', 'processInstanceId', processInstanceId);
            const localVarPath = `/api/process/instances/{processInstanceId}/nodes`
                .replace(`{${"processInstanceId"}}`, encodeURIComponent(String(processInstanceId)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Reassigns the current task of a process instance to a new assignee
         * @param {string} processInstanceId 
         * @param {string} newAssignee 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reassignTask: async (processInstanceId: string, newAssignee: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('reassignTask', 'processInstanceId', processInstanceId);
            assertParamExists('reassignTask', 'newAssignee', newAssignee);
            const localVarPath = `/api/process/instances/{processInstanceId}/reassign`
                .replace(`{${"processInstanceId"}}`, encodeURIComponent(String(processInstanceId)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            localVarRequestOptions.data = JSON.stringify({ newAssignee });

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ★★★ 關鍵修正：jumpToNode 傳送整個物件 JSON ★★★
         * Jumps the process instance to a specified node
         * @param {string} processInstanceId 
         * @param {TaskJumpRequest} taskJumpRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jumpToNode: async (processInstanceId: string, taskJumpRequest: TaskJumpRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('jumpToNode', 'processInstanceId', processInstanceId);
            assertParamExists('jumpToNode', 'taskJumpRequest', taskJumpRequest);
            const localVarPath = `/api/process/instances/{processInstanceId}/jump`
                .replace(`{${"processInstanceId"}}`, encodeURIComponent(String(processInstanceId)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            
            // ★★★ 重點：這裡必須是 JSON.stringify(taskJumpRequest) ★★★
            // 因為後端需要的是一個物件 { targetNode: "xxx", variables: {...} }
            localVarRequestOptions.data = JSON.stringify(taskJumpRequest);

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Downloads a BPMN process template file
         * @param {string} filename 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadTemplate: async (filename: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('downloadTemplate', 'filename', filename);
            const localVarPath = `/api/process/template/${filename}`;
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            localVarRequestOptions.responseType = 'blob'; 

            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...headersFromBaseOptions, ...options.headers };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ★★★ 新增：獲取流程歷程 ★★★
         * Retrieves execution history for a process instance
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProcessHistory: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('getProcessHistory', 'id', id);
            const localVarPath = `/api/process/instances/{id}/history`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    };
};

/**
 * ProcessAPIFp - 函数式编程接口
 */
export const ProcessAPIFp = function (configuration?: Configuration) {
    const localVarAxiosParamCreator = ProcessAPIAxiosParamCreator(configuration);
    return {
        async deployProcess(request: ProcessRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Process>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deployProcess(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProcessAPI.deployProcess']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        async getAllDefinitions(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Process[]>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllDefinitions(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProcessAPI.getAllDefinitions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        async getAllInstances(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Process[]>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllInstances(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProcessAPI.getAllInstances']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        async getMyProcessInstances(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Process[]>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyProcessInstances(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProcessAPI.getMyProcessInstances']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        async getProcessInstanceDiagram(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ bpmnXml: string, currentTask: string | null }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProcessInstanceDiagram(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProcessAPI.getProcessInstanceDiagram']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        async getProcessDefinitionDiagram(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ bpmnXml: string, currentTask: string | null }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProcessDefinitionDiagram(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProcessAPI.getProcessDefinitionDiagram']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        async getProcessFormFields(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FormField[]>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProcessFormFields(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProcessAPI.getProcessFormFields']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        async getNodeFormFields(processInstanceId: string, nodeId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FormField[]>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNodeFormFields(processInstanceId, nodeId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProcessAPI.getNodeFormFields']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        async getTaskFormFields(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FormField[]>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTaskFormFields(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProcessAPI.getTaskFormFields']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        async startProcess(request: ProcessRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Process>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.startProcess(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProcessAPI.startProcess']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        async toggleProcessStatus(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Process>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.toggleProcessStatus(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProcessAPI.toggleProcessStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        async getUsers(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User[]>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUsers(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProcessAPI.getUsers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        async getFlowNodes(processInstanceId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FlowNode[]>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFlowNodes(processInstanceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProcessAPI.getFlowNodes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        async reassignTask(processInstanceId: string, newAssignee: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reassignTask(processInstanceId, newAssignee, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProcessAPI.reassignTask']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        async jumpToNode(processInstanceId: string, taskJumpRequest: TaskJumpRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.jumpToNode(processInstanceId, taskJumpRequest, options);
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, basePath);
        },
        async downloadTemplate(filename: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Blob>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.downloadTemplate(filename, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProcessAPI.downloadTemplate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        async getProcessHistory(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HistoryLog[]>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProcessHistory(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProcessAPI.getProcessHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    };
};

/**
 * Request Interfaces (请求参数接口)
 */
export interface ProcessAPIDeployProcessRequest {
    readonly request: ProcessRequest;
}

export interface ProcessAPIGetProcessInstanceDiagramRequest {
    readonly id: string;
}

export interface ProcessAPIGetProcessDefinitionDiagramRequest {
    readonly id: string;
}

export interface ProcessAPIGetProcessFormFieldsRequest {
    readonly id: string;
}

export interface ProcessAPIGetTaskFormFieldsRequest {
    readonly id: string;
}

export interface ProcessAPIStartProcessRequest {
    readonly processRequest: ProcessRequest;
}

export interface ProcessAPIToggleProcessStatusRequest {
    readonly id: string;
}

export interface ProcessAPIGetFlowNodesRequest {
    readonly processInstanceId: string;
}

export interface ProcessAPIReassignTaskRequest {
    readonly processInstanceId: string;
    readonly newAssignee: string;
}

export interface ProcessAPIJumpToNodeRequest {
    readonly processInstanceId: string;
    readonly targetNode: string;
    readonly variables?: { [key: string]: any };
}

export interface ProcessAPIGetProcessHistoryRequest {
    readonly id: string;
}

/**
 * ProcessAPI - 面向对象的 API 类
 */
export class ProcessAPI extends BaseAPI {
    public deployProcess(requestParameters: ProcessAPIDeployProcessRequest, options?: RawAxiosRequestConfig) {
        return ProcessAPIFp(this.configuration).deployProcess(requestParameters.request, options).then((request) => request(this.axios, this.basePath));
    }

    public getAllDefinitions(options?: RawAxiosRequestConfig) {
        return ProcessAPIFp(this.configuration).getAllDefinitions(options).then((request) => request(this.axios, this.basePath));
    }

    public getAllInstances(options?: RawAxiosRequestConfig) {
        return ProcessAPIFp(this.configuration).getAllInstances(options).then((request) => request(this.axios, this.basePath));
    }

    public getMyProcessInstances(options?: RawAxiosRequestConfig) {
        return ProcessAPIFp(this.configuration).getMyProcessInstances(options).then((request) => request(this.axios, this.basePath));
    }

    public getProcessInstanceDiagram(requestParameters: ProcessAPIGetProcessInstanceDiagramRequest, options?: RawAxiosRequestConfig) {
        return ProcessAPIFp(this.configuration).getProcessInstanceDiagram(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    public getProcessDefinitionDiagram(requestParameters: ProcessAPIGetProcessDefinitionDiagramRequest, options?: RawAxiosRequestConfig) {
        return ProcessAPIFp(this.configuration).getProcessDefinitionDiagram(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    public getProcessFormFields(requestParameters: ProcessAPIGetProcessFormFieldsRequest, options?: RawAxiosRequestConfig) {
        return ProcessAPIFp(this.configuration).getProcessFormFields(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    public getNodeFormFields(processInstanceId: string, nodeId: string, options?: RawAxiosRequestConfig) {
        return ProcessAPIFp(this.configuration).getNodeFormFields(processInstanceId, nodeId, options).then((request) => request(this.axios, this.basePath));
    }

    public getTaskFormFields(requestParameters: ProcessAPIGetTaskFormFieldsRequest, options?: RawAxiosRequestConfig) {
        return ProcessAPIFp(this.configuration).getTaskFormFields(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    public startProcess(requestParameters: ProcessAPIStartProcessRequest, options?: RawAxiosRequestConfig) {
        return ProcessAPIFp(this.configuration).startProcess(requestParameters.processRequest, options).then((request) => request(this.axios, this.basePath));
    }

    public toggleProcessStatus(requestParameters: ProcessAPIToggleProcessStatusRequest, options?: RawAxiosRequestConfig) {
        return ProcessAPIFp(this.configuration).toggleProcessStatus(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    public getUsers(options?: RawAxiosRequestConfig) {
        return ProcessAPIFp(this.configuration).getUsers(options).then((request) => request(this.axios, this.basePath));
    }

    public getFlowNodes(requestParameters: ProcessAPIGetFlowNodesRequest, options?: RawAxiosRequestConfig) {
        return ProcessAPIFp(this.configuration).getFlowNodes(requestParameters.processInstanceId, options).then((request) => request(this.axios, this.basePath));
    }

    public reassignTask(requestParameters: ProcessAPIReassignTaskRequest, options?: RawAxiosRequestConfig) {
        return ProcessAPIFp(this.configuration).reassignTask(requestParameters.processInstanceId, requestParameters.newAssignee, options).then((request) => request(this.axios, this.basePath));
    }

    public jumpToNode(requestParameters: ProcessAPIJumpToNodeRequest, options?: RawAxiosRequestConfig) {
        // ★★★ 修正點：建構 TaskJumpRequest 物件，確保符合 API 定義 ★★★
        const taskJumpRequest: TaskJumpRequest = { 
            targetNode: requestParameters.targetNode, 
            variables: requestParameters.variables 
        };
        return ProcessAPIFp(this.configuration).jumpToNode(requestParameters.processInstanceId, taskJumpRequest, options).then((request) => request(this.axios, this.basePath));
    }

    public downloadTemplate(filename: string, options?: RawAxiosRequestConfig) {
        return ProcessAPIFp(this.configuration).downloadTemplate(filename, options).then((request) => request(this.axios, this.basePath));
    }

    public getProcessHistory(requestParameters: ProcessAPIGetProcessHistoryRequest, options?: RawAxiosRequestConfig) {
        return ProcessAPIFp(this.configuration).getProcessHistory(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }
}

// Data Interfaces (模型接口)
export interface TaskJumpRequest {
    targetNode: string;
    variables?: { [key: string]: any };
}

export interface FormField {
    key: string;
    label: string;
    type: 'text' | 'select' | 'number' | 'date' | 'switch';
    options?: { label: string; value: string }[];
    required?: boolean;
    value?: any;
    disabled?: boolean;
}

export interface FlowNode {
    id: string;
    name: string;
}

export interface User {
    label: string;
    value: string;
}

export interface HistoryLog {
    activityName?: string;
    activityType?: string;
    assignee?: string;
    startTime?: string;
    endTime?: string;
    duration?: string;
    status?: string;
    variables?: { [key: string]: any };
}