/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
import { DUMMY_BASE_URL, assertParamExists, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
import { BASE_PATH, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';

/**
 * TaskAPI - axios parameter creator
 * @export
 */
export const TaskAPIAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves tasks assigned to the current user
         * @summary Get user's tasks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyTasks: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/task/my-tasks`;
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ★★★ 新增：獲取可認領的群組任務 ★★★
         * Retrieves unassigned tasks for candidate groups
         * @summary Get group tasks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGroupTasks: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/task/group-tasks`;
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves completed tasks assigned to the current user
         * @summary Get user's history tasks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHistoryTasks: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/task/history-tasks`;
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ★★★ 新增：簽收任務 ★★★
         * Assign the task to the current user
         * @summary Claim a task
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        claimTask: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('claimTask', 'id', id);
            const localVarPath = `/api/task/{id}/claim`.replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ★★★ 新增：反簽收任務 ★★★
         * Release the task back to group
         * @summary Unclaim a task
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unclaimTask: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('unclaimTask', 'id', id);
            const localVarPath = `/api/task/{id}/unclaim`.replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves the form structure for a task
         * @summary Get task form
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTaskForm: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('getTaskForm', 'id', id);
            const localVarPath = `/api/task/{id}/form`.replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Reassigns a task to a new user
         * @summary Reassign task
         * @param {string} id
         * @param {TaskReassignRequest} taskReassignRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reassignTask: async (id: string, taskReassignRequest: TaskReassignRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('reassignTask', 'id', id);
            assertParamExists('reassignTask', 'taskReassignRequest', taskReassignRequest);
            const localVarPath = `/api/task/{id}/reassign`.replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            localVarRequestOptions.data = serializeDataIfNeeded(taskReassignRequest, localVarRequestOptions, configuration);

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Submits form data for a task
         * @summary Submit task form
         * @param {string} id
         * @param {TaskFormRequest} taskFormRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitTaskForm: async (id: string, taskFormRequest: TaskFormRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('submitTaskForm', 'id', id);
            assertParamExists('submitTaskForm', 'taskFormRequest', taskFormRequest);
            const localVarPath = `/api/task/{id}/submit`.replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            localVarRequestOptions.data = serializeDataIfNeeded(taskFormRequest, localVarRequestOptions, configuration);

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    };
};

/**
 * TaskAPI - functional programming interface
 * @export
 */
export const TaskAPIFp = function (configuration?: Configuration) {
    const localVarAxiosParamCreator = TaskAPIAxiosParamCreator(configuration);
    return {
        async getMyTasks(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TaskViewModel>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyTasks(options);
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, basePath);
        },
        // ★★★ 新增 ★★★
        async getGroupTasks(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TaskViewModel>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getGroupTasks(options);
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, basePath);
        },
        async getHistoryTasks(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TaskViewModel>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHistoryTasks(options);
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, basePath);
        },
        // ★★★ 新增 ★★★
        async claimTask(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.claimTask(id, options);
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, basePath);
        },
        // ★★★ 新增 ★★★
        async unclaimTask(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.unclaimTask(id, options);
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, basePath);
        },
        async getTaskForm(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<{ key: string; label: string; type: string; options?: Array<{ label: string; value: string }> }>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTaskForm(id, options);
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, basePath);
        },
        async reassignTask(id: string, taskReassignRequest: TaskReassignRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reassignTask(id, taskReassignRequest, options);
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, basePath);
        },
        async submitTaskForm(id: string, taskFormRequest: TaskFormRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.submitTaskForm(id, taskFormRequest, options);
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, basePath);
        },
    };
};

/**
 * TaskAPI - factory interface
 * @export
 */
export const TaskAPIFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TaskAPIFp(configuration);
    return {
        getMyTasks(options?: RawAxiosRequestConfig): AxiosPromise<Array<TaskViewModel>> {
            return localVarFp.getMyTasks(options).then((request) => request(axios, basePath));
        },
        // ★★★ 新增 ★★★
        getGroupTasks(options?: RawAxiosRequestConfig): AxiosPromise<Array<TaskViewModel>> {
            return localVarFp.getGroupTasks(options).then((request) => request(axios, basePath));
        },
        getHistoryTasks(options?: RawAxiosRequestConfig): AxiosPromise<Array<TaskViewModel>> {
            return localVarFp.getHistoryTasks(options).then((request) => request(axios, basePath));
        },
        // ★★★ 新增 ★★★
        claimTask(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.claimTask(id, options).then((request) => request(axios, basePath));
        },
        // ★★★ 新增 ★★★
        unclaimTask(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.unclaimTask(id, options).then((request) => request(axios, basePath));
        },
        getTaskForm(requestParameters: TaskAPIGetTaskFormRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<{ key: string; label: string; type: string; options?: Array<{ label: string; value: string }> }>> {
            return localVarFp.getTaskForm(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        reassignTask(requestParameters: TaskAPIReassignTaskRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.reassignTask(requestParameters.id, requestParameters.taskReassignRequest, options).then((request) => request(axios, basePath));
        },
        submitTaskForm(requestParameters: TaskAPISubmitTaskFormRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.submitTaskForm(requestParameters.id, requestParameters.taskFormRequest, options).then((request) => request(axios, basePath));
        },
    };
};

export interface TaskAPIGetTaskFormRequest {
    readonly id: string;
}

export interface TaskAPIReassignTaskRequest {
    readonly id: string;
    readonly taskReassignRequest: TaskReassignRequest;
}

export interface TaskAPISubmitTaskFormRequest {
    readonly id: string;
    readonly taskFormRequest: TaskFormRequest;
}

export class TaskAPI extends BaseAPI {
    public getMyTasks(options?: RawAxiosRequestConfig) {
        return TaskAPIFp(this.configuration).getMyTasks(options).then((request) => request(this.axios, this.basePath));
    }
    // ★★★ 新增 ★★★
    public getGroupTasks(options?: RawAxiosRequestConfig) {
        return TaskAPIFp(this.configuration).getGroupTasks(options).then((request) => request(this.axios, this.basePath));
    }
    public getHistoryTasks(options?: RawAxiosRequestConfig) {
        return TaskAPIFp(this.configuration).getHistoryTasks(options).then((request) => request(this.axios, this.basePath));
    }
    // ★★★ 新增 ★★★
    public claimTask(id: string, options?: RawAxiosRequestConfig) {
        return TaskAPIFp(this.configuration).claimTask(id, options).then((request) => request(this.axios, this.basePath));
    }
    // ★★★ 新增 ★★★
    public unclaimTask(id: string, options?: RawAxiosRequestConfig) {
        return TaskAPIFp(this.configuration).unclaimTask(id, options).then((request) => request(this.axios, this.basePath));
    }
    public getTaskForm(requestParameters: TaskAPIGetTaskFormRequest, options?: RawAxiosRequestConfig) {
        return TaskAPIFp(this.configuration).getTaskForm(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }
    public reassignTask(requestParameters: TaskAPIReassignTaskRequest, options?: RawAxiosRequestConfig) {
        return TaskAPIFp(this.configuration).reassignTask(requestParameters.id, requestParameters.taskReassignRequest, options).then((request) => request(this.axios, this.basePath));
    }
    public submitTaskForm(requestParameters: TaskAPISubmitTaskFormRequest, options?: RawAxiosRequestConfig) {
        return TaskAPIFp(this.configuration).submitTaskForm(requestParameters.id, requestParameters.taskFormRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

export interface TaskFormRequest {
    formData: { [key: string]: any };
}

export interface TaskReassignRequest {
    assignee: string;
}

// 補上 TaskViewModel 介面，避免 any
export interface TaskViewModel {
    id: string;
    name: string;
    processName: string;
    assignee: string;
    createTime: string;
    processInstanceId: string;
    currentAssignee?: string;
}