/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request object for jumping to a specific task
 * @export
 * @interface TaskJumpRequest
 */
export interface TaskJumpRequest {
    /**
     * ID of the target task
     * @type {string}
     * @memberof TaskJumpRequest
     */
    'targetTaskId': string;
}

