/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request object for reassigning a task
 * @export
 * @interface TaskReassignRequest
 */
export interface TaskReassignRequest {
    /**
     * Username of the new assignee
     * @type {string}
     * @memberof TaskReassignRequest
     */
    'assignee': string;
}

