/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request object for creating a todo task
 * @export
 * @interface TodoRequest
 */
export interface TodoRequest {
    /**
     * Title of the todo task
     * @type {string}
     * @memberof TodoRequest
     */
    'title': string;
    /**
     * Description of the todo task
     * @type {string}
     * @memberof TodoRequest
     */
    'description'?: string;
    /**
     * Username of the assignee
     * @type {string}
     * @memberof TodoRequest
     */
    'assignee'?: string;
}

