/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Todo
 */
export interface Todo {
    /**
     * 
     * @type {number}
     * @memberof Todo
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Todo
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Todo
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof Todo
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof Todo
     */
    'processInstanceId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Todo
     */
    'processDefinitionId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Todo
     */
    'assignee'?: string;
}

